enum tnumber {
	TEOF, TONECMT, TMULCMT, TIDENT, TDECIMAL, TFIXED, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TPLUS, TMINUS, TSTAR, TSLASH, TMOD, TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSGIN, TNOT, TAND, TOR, TEQUAL, TNOTEQU, TLESS, TOVER, TLESSE, TOVERE, TINC, TDEC, TOSBRA, TCSBRA, TCOMMA, TOMBRA, TCMBRA, TOLBRA, TCLBRA, TSEMI, TBLANK, TTAB, TNEWLINE
};